// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bridge is the Wails service exposed to the frontend. Its exported methods are
 * callable from TypeScript and provide all filesystem, link-resolution and
 * navigation logic, keeping the webview a pure presentation layer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Backlinks returns documents that link to the given file.
 */
export function Backlinks(path: string): $CancellablePromise<core$0.Backlink[] | null> {
    return $Call.ByID(2567920537, path);
}

/**
 * Init returns the bootstrap information for the frontend.
 */
export function Init(): $CancellablePromise<$models.InitInfo> {
    return $Call.ByID(997768705);
}

/**
 * OpenExternal opens a URL or non-markdown file with the OS default handler.
 */
export function OpenExternal(target: string): $CancellablePromise<string> {
    return $Call.ByID(1764564136, target);
}

/**
 * OpenInNewWindow launches a separate mdv process for the given path.
 */
export function OpenInNewWindow(path: string): $CancellablePromise<string> {
    return $Call.ByID(262853242, path);
}

/**
 * ReadDocument loads a markdown document from disk.
 */
export function ReadDocument(path: string): $CancellablePromise<$models.DocumentDTO> {
    return $Call.ByID(4167214878, path);
}

/**
 * ResolveLink classifies a raw href against the directory of the current doc.
 */
export function ResolveLink(raw: string, currentDir: string): $CancellablePromise<$models.LinkTargetDTO> {
    return $Call.ByID(1030816277, raw, currentDir);
}

/**
 * WatchFile switches the live-reload watcher to the given document.
 */
export function WatchFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1121063624, path);
}
