// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bridge is the Wails service exposed to the frontend. Its exported methods are
 * callable from TypeScript and provide all filesystem, link-resolution and
 * navigation logic, keeping the webview a pure presentation layer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyExcludes stores the navigator exclusion patterns and enabled flag,
 * persists them (debounced) and returns the absolute paths of the workspace
 * documents that are currently excluded. When disabled it returns an empty
 * list, leaving every document visible while still remembering the patterns.
 */
export function ApplyExcludes(text: string, enabled: boolean): $CancellablePromise<string[] | null> {
    return $Call.ByID(1416857530, text, enabled);
}

/**
 * Backlinks returns documents that link to the given file.
 */
export function Backlinks(path: string): $CancellablePromise<core$0.Backlink[] | null> {
    return $Call.ByID(2567920537, path);
}

/**
 * ClearRecent empties the rolling recently-opened list and returns the (now
 * empty) list so the frontend can refresh the toolbar drop-down.
 */
export function ClearRecent(): $CancellablePromise<$models.RecentItem[] | null> {
    return $Call.ByID(3389475587);
}

/**
 * Init returns the bootstrap information for the frontend.
 */
export function Init(): $CancellablePromise<$models.InitInfo> {
    return $Call.ByID(997768705);
}

/**
 * IsDefaultHandler reports whether mdv is the operating system's default
 * application for the type of the file at path. The GUI uses it to decide
 * whether to show the "open in the associated app" toolbar button: that button
 * is only useful when something other than mdv would open the file.
 */
export function IsDefaultHandler(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1041764512, path);
}

/**
 * OpenExternal opens a URL or non-markdown file with the OS default handler.
 * As a defense-in-depth backstop (the frontend already confirms with the user),
 * only a small allow-list of schemes is permitted so a crafted document cannot
 * hand an arbitrary scheme (e.g. an app-launching custom protocol) to the OS.
 */
export function OpenExternal(target: string): $CancellablePromise<string> {
    return $Call.ByID(1764564136, target);
}

/**
 * OpenInNewWindow launches a separate mdv process for the given path. An
 * optional fragment (anchor slug, without '#') makes the new window scroll to a
 * specific section after loading.
 */
export function OpenInNewWindow(path: string, fragment: string): $CancellablePromise<string> {
    return $Call.ByID(262853242, path, fragment);
}

/**
 * ReadDocument loads a markdown document from disk, enforcing the shared
 * maximum document size so the webview never tries to render an oversized file.
 */
export function ReadDocument(path: string): $CancellablePromise<$models.DocumentDTO> {
    return $Call.ByID(4167214878, path);
}

/**
 * RefreshWorkspace re-scans the workspace directory and returns the current
 * markdown document listing, so the navigator can update after files are added,
 * removed or renamed on disk.
 */
export function RefreshWorkspace(): $CancellablePromise<$models.DocFileDTO[] | null> {
    return $Call.ByID(1335438411);
}

/**
 * Reinit re-resolves path as the program's input and refreshes the workspace
 * listing, so a file or folder dropped onto the window replaces what mdv is
 * viewing without restarting the process. It returns fresh bootstrap info (the
 * network update check is skipped); live UI settings are preserved by the
 * frontend. An unreadable selection leaves the current input unchanged.
 */
export function Reinit(path: string): $CancellablePromise<$models.InitInfo> {
    return $Call.ByID(4013319924, path);
}

/**
 * ResetLayout restores the window to its default size (centered) and the side
 * panels to their default widths, persisting the result. It returns the default
 * panel widths so the frontend can update its CSS variables.
 */
export function ResetLayout(): $CancellablePromise<$models.LayoutDTO> {
    return $Call.ByID(2586955248);
}

/**
 * ResolveAsset resolves a local image/media reference (e.g. "images/icon.png")
 * against the directory of the current document and returns it as a data URI so
 * the webview can display it. The embedded asset server only serves the
 * compiled frontend, so relative filesystem paths must be inlined here.
 * 
 * Absolute URLs (http(s), data:, etc.) and unreadable/oversized files return
 * an empty string, leaving the original reference untouched.
 */
export function ResolveAsset(src: string, currentDir: string): $CancellablePromise<string> {
    return $Call.ByID(1869993087, src, currentDir);
}

/**
 * ResolveLink classifies a raw href against the directory of the current doc.
 */
export function ResolveLink(raw: string, currentDir: string): $CancellablePromise<$models.LinkTargetDTO> {
    return $Call.ByID(1030816277, raw, currentDir);
}

/**
 * SaveExtendedSyntax persists the user's runtime choice for the extended inline
 * Markdown syntax toggle to state.jsonc so it is restored on the next launch
 * and shared with the terminal UI.
 */
export function SaveExtendedSyntax(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1123759844, enabled);
}

/**
 * SaveLayout records the current side-panel widths (in pixels). The store
 * debounces the write, so the frontend may call this freely on every drag.
 */
export function SaveLayout(sidebarWidth: number, tocWidth: number): $CancellablePromise<void> {
    return $Call.ByID(1777614844, sidebarWidth, tocWidth);
}

/**
 * SearchContent runs a streaming, case-insensitive fuzzy-phrase content search
 * over the workspace markdown files. Results are delivered to the
 * frontend as "content-search:result" events (one per matching document) and a
 * final "content-search:done" event. Each call cancels any in-flight search.
 * The caller passes a generation number that is echoed back in every event so
 * the frontend can discard results from a superseded search.
 */
export function SearchContent(query: string, gen: number): $CancellablePromise<void> {
    return $Call.ByID(3919112416, query, gen);
}

/**
 * SetWatchEnabled turns the active-document auto-reload watcher on or off at
 * runtime. When enabling, path (the currently displayed document) is armed
 * immediately; when disabling, the active-document watch is released. It returns
 * the resulting enabled state.
 */
export function SetWatchEnabled(enabled: boolean, path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2697151537, enabled, path);
}

/**
 * WatchFile switches the live-reload watcher to the given document. It is a
 * no-op while auto-reload is disabled (the default).
 */
export function WatchFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1121063624, path);
}
