// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bridge is the Wails service exposed to the frontend. Its exported methods are
 * callable from TypeScript and provide all filesystem, link-resolution and
 * navigation logic, keeping the webview a pure presentation layer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Backlinks returns documents that link to the given file.
 */
export function Backlinks(path: string): $CancellablePromise<core$0.Backlink[] | null> {
    return $Call.ByID(2567920537, path);
}

/**
 * Init returns the bootstrap information for the frontend.
 */
export function Init(): $CancellablePromise<$models.InitInfo> {
    return $Call.ByID(997768705);
}

/**
 * OpenExternal opens a URL or non-markdown file with the OS default handler.
 */
export function OpenExternal(target: string): $CancellablePromise<string> {
    return $Call.ByID(1764564136, target);
}

/**
 * OpenInNewWindow launches a separate mdv process for the given path. An
 * optional fragment (anchor slug, without '#') makes the new window scroll to a
 * specific section after loading.
 */
export function OpenInNewWindow(path: string, fragment: string): $CancellablePromise<string> {
    return $Call.ByID(262853242, path, fragment);
}

/**
 * ReadDocument loads a markdown document from disk, enforcing the shared
 * maximum document size so the webview never tries to render an oversized file.
 */
export function ReadDocument(path: string): $CancellablePromise<$models.DocumentDTO> {
    return $Call.ByID(4167214878, path);
}

/**
 * ResetLayout restores the window to its default size (centered) and the side
 * panels to their default widths, persisting the result. It returns the default
 * panel widths so the frontend can update its CSS variables.
 */
export function ResetLayout(): $CancellablePromise<$models.LayoutDTO> {
    return $Call.ByID(2586955248);
}

/**
 * ResolveAsset resolves a local image/media reference (e.g. "images/icon.png")
 * against the directory of the current document and returns it as a data URI so
 * the webview can display it. The embedded asset server only serves the
 * compiled frontend, so relative filesystem paths must be inlined here.
 * 
 * Absolute URLs (http(s), data:, etc.) and unreadable/oversized files return
 * an empty string, leaving the original reference untouched.
 */
export function ResolveAsset(src: string, currentDir: string): $CancellablePromise<string> {
    return $Call.ByID(1869993087, src, currentDir);
}

/**
 * ResolveLink classifies a raw href against the directory of the current doc.
 */
export function ResolveLink(raw: string, currentDir: string): $CancellablePromise<$models.LinkTargetDTO> {
    return $Call.ByID(1030816277, raw, currentDir);
}

/**
 * SaveLayout records the current side-panel widths (in pixels). The store
 * debounces the write, so the frontend may call this freely on every drag.
 */
export function SaveLayout(sidebarWidth: number, tocWidth: number): $CancellablePromise<void> {
    return $Call.ByID(1777614844, sidebarWidth, tocWidth);
}

/**
 * SearchContent runs a streaming, case-insensitive AND-per-document content
 * search over the workspace markdown files. Results are delivered to the
 * frontend as "content-search:result" events (one per matching document) and a
 * final "content-search:done" event. Each call cancels any in-flight search.
 * The caller passes a generation number that is echoed back in every event so
 * the frontend can discard results from a superseded search.
 */
export function SearchContent(query: string, gen: number): $CancellablePromise<void> {
    return $Call.ByID(3919112416, query, gen);
}

/**
 * WatchFile switches the live-reload watcher to the given document.
 */
export function WatchFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1121063624, path);
}
