// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";

/**
 * DocFileDTO is the frontend-facing shape of a workspace document.
 */
export interface DocFileDTO {
    "path": string;
    "name": string;
    "title": string;
    "rel": string;
}

/**
 * DocumentDTO is a loaded document.
 */
export interface DocumentDTO {
    "path": string;
    "dir": string;
    "name": string;
    "markdown": string;
    "error": string;
}

/**
 * InitInfo is returned on startup to bootstrap the UI.
 */
export interface InitInfo {
    /**
     * "file" | "folder"
     */
    "kind": string;
    "path": string;
    "dir": string;
    "fragment": string;
    "appName": string;
    "version": string;
    "config": core$0.Defaults;
    "workspace": DocFileDTO[] | null;
    "update": UpdateDTO;
    "layout": LayoutDTO;
}

/**
 * LayoutDTO carries the persisted side-panel widths (in pixels) so the frontend
 * can apply them before the first paint, avoiding panels jumping after start.
 */
export interface LayoutDTO {
    "sidebarWidth": number;
    "tocWidth": number;
}

/**
 * LinkTargetDTO is the resolved classification of a link.
 */
export interface LinkTargetDTO {
    "kind": string;
    "resolved": string;
    "fragment": string;
    "display": string;
    "raw": string;
}

/**
 * UpdateDTO carries version-check results to the status bar.
 */
export interface UpdateDTO {
    "available": boolean;
    "latest": string;
    "downloadUrl": string;
}
