// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";

/**
 * DocFileDTO is the frontend-facing shape of a workspace document.
 */
export interface DocFileDTO {
    "path": string;
    "name": string;
    "title": string;
    "rel": string;
}

/**
 * DocumentDTO is a loaded document.
 */
export interface DocumentDTO {
    "path": string;
    "dir": string;
    "name": string;
    "markdown": string;
    "error": string;
}

/**
 * InitInfo is returned on startup to bootstrap the UI.
 */
export interface InitInfo {
    /**
     * "file" | "folder"
     */
    "kind": string;
    "path": string;
    "dir": string;
    "fragment": string;
    "appName": string;
    "version": string;
    "author": string;
    "copyright": string;
    "repoURL": string;
    "config": core$0.Defaults;
    "workspace": DocFileDTO[] | null;
    "update": UpdateDTO;
    "layout": LayoutDTO;

    /**
     * Recent is the rolling list of recently opened files and folders (mixed,
     * most recent first), surfaced in the toolbar's recents drop-down.
     */
    "recent": RecentItem[] | null;

    /**
     * ExtendedSyntax is the effective state of the opt-in "extended" inline
     * Markdown syntax (math, sub/sup, highlight, inserted): the persisted runtime
     * choice from state.jsonc if the user ever toggled it, otherwise the
     * settings.jsonc default.
     */
    "extendedSyntax": boolean;

    /**
     * RemoteImages is true when mdv was started with --remote, so the frontend
     * begins the session with remote (http/https) image loading enabled and the
     * toolbar toggle shown active.
     */
    "remoteImages": boolean;

    /**
     * SidePanel is true when mdv was started with --sidepanel, so the frontend
     * keeps the document navigator panel visible even when a single file is
     * opened (including files opened later via File ▸ Open).
     */
    "sidePanel": boolean;
}

/**
 * LayoutDTO carries the persisted side-panel widths (in pixels) so the frontend
 * can apply them before the first paint, avoiding panels jumping after start.
 */
export interface LayoutDTO {
    "sidebarWidth": number;
    "tocWidth": number;

    /**
     * ExcludePatterns is the persisted navigator exclusion text (one pattern per
     * line) and ExcludeEnabled whether it is currently applied.
     */
    "excludePatterns": string;
    "excludeEnabled": boolean;
}

/**
 * LinkTargetDTO is the resolved classification of a link.
 */
export interface LinkTargetDTO {
    "kind": string;
    "resolved": string;
    "fragment": string;
    "display": string;
    "raw": string;
}

/**
 * RecentItem is a single entry in the rolling list of recently opened inputs.
 * Files and folders share one list; Kind ("file" or "folder") only affects how
 * the entry is labelled in the toolbar's recents drop-down.
 */
export interface RecentItem {
    "path": string;
    "kind": string;
}

/**
 * UpdateDTO carries version-check results to the status bar.
 */
export interface UpdateDTO {
    "available": boolean;
    "latest": string;
    "downloadUrl": string;
}
