// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backlink is a reference from one workspace document to another.
 */
export interface Backlink {
    /**
     * SourcePath is the absolute path of the document containing the link.
     */
    "sourcePath": string;

    /**
     * SourceName is the base file name of the source document.
     */
    "sourceName": string;

    /**
     * SourceTitle is the H1 title of the source document, if known.
     */
    "sourceTitle": string;

    /**
     * Line is the 1-based line number where the link occurs.
     */
    "line": number;

    /**
     * Snippet is the trimmed source line for context.
     */
    "snippet": string;
}

/**
 * Defaults holds every tunable setting. Values here are the hard-coded,
 * developer-configurable defaults. Anything a user is allowed to change lives
 * in ~/.config/mdv/settings.jsonc and is merged over these at startup.
 * 
 * Fields that are intentionally NOT user-configurable today still live here so
 * a future release can expose them without code churn.
 */
export interface Defaults {
    /**
     * Appearance.
     * "system" | "light" | "dark"
     */
    "theme": string;

    /**
     * syntax highlight theme name (GUI)
     */
    "codeTheme": string;

    /**
     * empty => OS default UI/serif font
     */
    "fontFamily": string;

    /**
     * base content font size
     */
    "fontSizePx": number;

    /**
     * unit-less line-height multiplier
     */
    "lineHeight": number;

    /**
     * max readable column width
     */
    "contentWidthPx": number;

    /**
     * use a monospaced content font
     */
    "monospace": boolean;

    /**
     * console/TUI wrap cap in columns (0 = no cap)
     */
    "maxWidth": number;

    /**
     * Behaviour.
     * "filename" | "title"
     */
    "navLabelMode": string;

    /**
     * open http links in OS browser
     */
    "followExternal": boolean;

    /**
     * initial state of the active-document auto-reload toggle
     */
    "liveReload": boolean;

    /**
     * zoom increment per +/- step
     */
    "zoomStep": number;
    "minZoom": number;
    "maxZoom": number;

    /**
     * Terminal image rendering (console/TUI):
     *   "auto"     pick the best method the terminal supports
     *   "graphics" force a pixel protocol (kitty/iTerm2/sixel)
     *   "blocks"   force the Unicode half-block renderer
     *   "off"      show alt text only
     */
    "images": string;

    /**
     * ImagesRemote allows fetching http(s) images in the console/TUI. Off by
     * default so a document from an untrusted source cannot silently fetch remote
     * content (tracking pixels, IP/User-Agent leakage); enable it explicitly here
     * or toggle it for the session in the TUI with the 'i' key.
     */
    "imagesRemote": boolean;

    /**
     * Updates.
     */
    "checkForUpdates": boolean;

    /**
     * "owner/repo" on GitHub
     */
    "updateRepo": string;

    /**
     * min hours between checks
     */
    "updateCheckHours": number;

    /**
     * Markdown extensions (all on by default).
     */
    "enableMath": boolean;
    "enableMermaid": boolean;
    "enableEmoji": boolean;
    "enableWikilinks": boolean;
    "enableFootnotes": boolean;
    "enableAlerts": boolean;
    "enableAzureDevOps": boolean;

    /**
     * EnableExtendedSyntax turns on the "character-stealing" inline extensions
     * that are off by default because they can silently transform ordinary
     * prose: math ($...$, $$...$$, ```math), subscript (~x~), superscript (^x^),
     * highlight (==x==) and inserted (++x++). All other extensions stay on. This
     * is the default value; users can flip it live (GUI toolbar button / TUI 'x'
     * shortcut), in which case the runtime choice is persisted in state.jsonc and
     * takes precedence over this setting. Only affects the GUI renderer; the
     * terminal engine cannot render these constructs.
     */
    "enableExtendedSyntax": boolean;

    /**
     * Files recognised as markdown documents in folder navigation.
     */
    "markdownExtensions": string[] | null;
}
